### PR TITLE
Modify ESP32S3-BZM-TFT35_GT911 to SPI screen

### PR DESCRIPTION
**Pull request by liqijian101**
I have modified ESP32S3-BZM-TFT35_GT911 to SPI screen.
However, the following error is currently being prompted:
```
ESP-ERROR-CHECK failed: esp_err_t 0x105 (ESP-ERR-NOT-FOUND) at 0x4202ccda
File: "./main/modules/serial/esp3d_serial_client. cpp" line 165
Func: virtual bool ESP3DSerialClient:: begin()
Expression: uart_driver-install (ESP3D-SERIAL-PORT, ESP3D-SERIAL-RX-BUFFER-SIZE * 2, ESP3D-SERIAL-TX-BUFFER-SIZE, 0, NULL, intr-alloc_flags)
Abort() was called at PC 0x4037f973 on core 0
```
**If I annotate the following code for esp3d_tft.cpp，there will be no errors**
`success = esp3dTftstream.begin();`

### CODE REVIEW

**Comment by luc-github** [comment]
@liqijian101  please check my fix

**Comment by liqijian101** [comment]
It's not a compilation error. It returns an error message on the serial port
error

**Comment by luc-github** [comment]
Well before it was not compiling neither

If it is runtime error I do not have your board so I cannot reproduce - more over serial is same for all boards so it may be wiring issue / pin conflict 
Did you try basic arduino sketch for serial  on this board to valicdate it works ?

**Comment by liqijian101** [comment]
Before this update, I was able to run all functions correctly, including TFT, camera, and serial port

**Comment by luc-github** [comment]
it is not same board if you changed so many pins -  I see you even changed sdkconfig - the issue is may be there

**Comment by liqijian101** [comment]
It seems that interrupts cannot be allocated. The problem may not necessarily be with the serial port here, it may be that the interrupt is occupied elsewhere

**Comment by luc-github** [comment]
Yes as I mention you modified sdkconfig,  revert it because several changes make no sense

**Comment by liqijian101** [comment]
> revert it because several changes make no sense

Having the same problem。

**Comment by luc-github** [comment]
Try using same value as esp32 : `.dma_channel = 1, ` instead of Auto

Sorry without board to test, I dry to guess

**Comment by luc-github** [comment]
yes seems 1 and 2 are  only for ESP32 and you are using S3
```
typedef enum {
  SPI_DMA_DISABLED = 0,     ///< Do not enable DMA for SPI
#if CONFIG_IDF_TARGET_ESP32
  SPI_DMA_CH1      = 1,     ///< Enable DMA, select DMA Channel 1
  SPI_DMA_CH2      = 2,     ///< Enable DMA, select DMA Channel 2
#endif
  SPI_DMA_CH_AUTO  = 3,     ///< Enable DMA, channel is automatically selected by driver
} spi_common_dma_t;
```
try with 0 then

**Comment by luc-github** [comment]
also if now you drop the rgb /i80 screen to use spi  you better disable related settings in sdkconfig

**Comment by liqijian101** [comment]
After disabling DMA, TFT refresh is very slow and cannot solve this issues.

**Comment by luc-github** [comment]
then keep dma auto and search in sdkconfig what could cause the issue

**Comment by liqijian101** [comment]
I think disabling the INT of the GT911 is sufficient. After testing, no impact was found

**Comment by luc-github** [comment]
> I think disabling the INT of the GT911 is sufficient. After testing, no impact was found

Ok if you think it is the solution - just let me know when your PR is ready to be merged 

Also does it make your previous board end of Life ?
Also what about http://esp3d.io/esp3d-tft/v1.x/hardware/esp32-s3/bzm-35-4832/index.html ?

**Comment by liqijian101** [comment]
> > I think disabling the INT of the GT911 is sufficient. After testing, no impact was found
> 
> Ok if you think it is the solution - just let me know when your PR is ready to be merged
> 
> Also does it make your previous board end of Life ? Also what about http://esp3d.io/esp3d-tft/v1.x/hardware/esp32-s3/bzm-35-4832/index.html ?

Yes,the  PR is ready to be merged。
The previous motherboard will be discarded, and I will update it

**Comment by liqijian101** [comment]
Now, except for the USB HOST CDC not working properly, everything else is working properly。
I found that the initialization code for usb_serial is not completely consistent with the instance
https://github.com/espressif/esp-idf/blob/master/examples/peripherals/usb/host/cdc/cdc_acm_vcp/main/cdc_acm_vcp_example_main.cpp

**Comment by luc-github** [comment]
what is the issue ?
be noted reference code should be 5.1 not master
https://github.com/espressif/esp-idf/blob/release/v5.1/examples/peripherals/usb/host/cdc/cdc_acm_vcp/main/cdc_acm_vcp_example_main.cpp

**Comment by liqijian101** [comment]
Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0x1a (SPI_FAST_FLASH_BOOT)
Saved PC:0x40385a17
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x508
load:0x403c9700,len:0x4
load:0x403c9704,len:0xad0
load:0x403cc700,len:0x288c
entry 0x403c9880
ESP_ERROR_CHECK failed: esp_err_t 0x105 (ESP_ERR_NOT_FOUND) at 0x42084661
file: "./managed_components/espressif__usb_host_cdc_acm/cdc_acm_host.c" line 897
func: cdc_acm_host_close
expression: cdc_acm_reset_transfer_endpoint(cdc_dev->dev_hdl, cdc_dev->data.in_xfer)

abort() was called at PC 0x40382cfb on core 1


Backtrace: 0x40379d32:0x3fcd1a90 0x40382d05:0x3fcd1ab0 0x4038a242:0x3fcd1ad0 0x40382cfb:0x3fcd1b40 0x42084661:0x3fcd1b70 0x4209b2df:0x3fcd1b90 0x4209b304:0x3fcd1bb0 0x4209b311:0x3fcd1bd0 0x4215d82d:0x3fcd1bf0 0x4202fd54:0x3fcd1c10 0x4202fdb1:0x3fcd1c60

**Comment by luc-github** [comment]
what idf core are you using ?

**Comment by liqijian101** [comment]
5.1.2

**Comment by luc-github** [comment]
do you have same issue if you disable TFT and camera ?
```-
# #######################################
# Select the Features
# #######################################
OPTION(ESP3D_AUTHENTICATION "Authentication on all clients" OFF)
OPTION(DISABLE_SERIAL_AUTHENTICATION "Disable Serial Authentication" ON)
OPTION(TIME_SERVICE  "Time service" ON)
OPTION(SSDP_SERVICE "SSDP service" ON)
OPTION(MDNS_SERVICE "MDNS service" ON)
OPTION(WIFI_SERVICE "WiFi service" ON)
OPTION(BT_SERVICE "Bluetooth service" OFF)
OPTION(WEB_SERVICES "Web Services http/websocket/webdav/camera" ON)
OPTION(CAMERA_SERVICE "Camera service" OFF)
OPTION(WEBDAV_SERVICES "WebDav Services" OFF)
OPTION(TELNET_SERVICE "Telnet service" OFF)
OPTION(WS_SERVICE "WebSocket data service" ON)
OPTION(TFT_UI_SERVICE "TFT UI service" OFF)
OPTION(SD_CARD_SERVICE "SD card service" ON)
OPTION(NOTIFICATIONS_SERVICE "Notifications service" ON)
OPTION(UPDATE_SERVICE "Update service" ON)
OPTION(USB_SERIAL_SERVICE "Use USB Serial if Available" ON)
OPTION(USE_FAT_INSTEAD_OF_LITTLEFS "Use FAT instead of LittleFS" OFF)
```

**Comment by liqijian101** [comment]
It is the same problem

> do you have same issue if you disable TFT and camera ?

**Comment by luc-github** [comment]
ok because like this I may try to reproduce on normal S3 because no more hardware dependency
Will check today

**Comment by luc-github** [comment]
Using a ESP32-S3 
```
# #######################################
# Select the targeted hardware
# #######################################

# With TFT:
OPTION(ESP32S3_HMI43V3 "TFT TARGET is ESP32S3 HMI 4.3inches" OFF)
OPTION(ESP32_ROTRICS_DEXARM35 "TFT TARGET is ESP32 Rotrics DexArm 3.5inches" OFF)
OPTION(ESP32S3_ZX3D50CE02S_USRC_4832 "TFT TARGET is ESP32S3 Panlee ZX3D50CE02S-SRC-4832 3.5inches" OFF)
OPTION(ESP32S3_BZM_TFT35_GT911 "TFT TARGET is ESP32S3 Panlee BZM 3.5inches" ON)
OPTION(ESP32S3_8048S070C "TFT TARGET is ESP32S3_8048S070C - 7.0in. 800x480 (Capacitive)" OFF)
OPTION(ESP32S3_8048S050C "TFT TARGET is ESP32S3_8048S050C - 5.0in. 800x480 (Capacitive)" OFF)
OPTION(ESP32S3_8048S043C "TFT TARGET is ESP32S3_8048S043C - 4.3in. 800x480 (Capacitive)" OFF)
OPTION(ESP32S3_4827S043C "TFT TARGET is ESP32S3_4827S043C - 4.3in. 480x272 (Capacitive)" OFF)
OPTION(ESP32_3248S035C "TFT TARGET is ESP32_3248S035C - 3.5in. 480x320 (Capacitive)" OFF)
OPTION(ESP32_3248S035R "TFT TARGET is ESP32_3248S035R - 3.5in. 480x320 (Resistive)"  OFF)
OPTION(ESP32_2432S028R "TFT TARGET is ESP32_2432S028R - 2.8in. 320x240 (Resistive)" OFF)

# Without TFT:
OPTION(ESP32S3_FREENOVE_1_1 "HARDWARE TARGET is ESP32S3 Freenove v1.1" OFF)
OPTION(ESP32S3_SEEED_STUDIO_XIAO  "HARDWARE TARGET is ESP32S3 Seeed Studio Xiao Sense" OFF)
OPTION(ESP32S3_CUSTOM "HARDWARE TARGET is ESP32S3 custom board" OFF)
OPTION(ESP32_CUSTOM "HARDWARE TARGET is ESP32 custom board" OFF)


# #######################################
# Optionally: Select hardware mods applied
# #######################################
#only for ESP32S3_8048S070C OR ESP32S3_8048S050C OR ESP32S3_8048S043C OR ESP32S3_4827S043C OR ESP32_3248S035C
OPTION(HARDWARE_MOD_GT911_INT "Hardware Mod: GT911 INT pin" OFF)

#Only for ESP32_3248S035C OR ESP32_3248S035R OR ESP32_2432S028R
# 4MB Flash, no PSRAM by default
OPTION(HARDWARE_MOD_8MB_FLASH "Hardware Mod: 8MB Flash Upgrade" OFF)
OPTION(HARDWARE_MOD_16MB_FLASH "Hardware Mod: 16MB Flash Upgrade" OFF)
OPTION(HARDWARE_MOD_EXT_PSRAM "Hardware Mod: External PSRAM" OFF)



# #######################################
# Select the targeted firmware
# #######################################
OPTION(TARGET_FW_MARLIN "Marlin firmware" ON)
OPTION(TARGET_FW_REPETIER "Repetier firmware" OFF)
OPTION(TARGET_FW_SMOOTHIEWARE "Smoothieware firmware" OFF)
OPTION(TARGET_FW_GRBL "GRBL firmware" OFF)


# #######################################
# Select the Features
# #######################################
OPTION(ESP3D_AUTHENTICATION "Authentication on all clients" OFF)
OPTION(DISABLE_SERIAL_AUTHENTICATION "Disable Serial Authentication" ON)
OPTION(TIME_SERVICE  "Time service" ON)
OPTION(SSDP_SERVICE "SSDP service" ON)
OPTION(MDNS_SERVICE "MDNS service" ON)
OPTION(WIFI_SERVICE "WiFi service" ON)
OPTION(BT_SERVICE "Bluetooth service" ON)
OPTION(WEB_SERVICES "Web Services http/websocket/webdav/camera" ON)
OPTION(CAMERA_SERVICE "Camera service" OFF)
OPTION(WEBDAV_SERVICES "WebDav Services" ON)
OPTION(TELNET_SERVICE "Telnet service" ON-)
OPTION(WS_SERVICE "WebSocket data service" ON)
OPTION(TFT_UI_SERVICE "TFT UI service" OFF)
OPTION(SD_CARD_SERVICE "SD card service" ON)
OPTION(NOTIFICATIONS_SERVICE "Notifications service" ON)
OPTION(UPDATE_SERVICE "Update service" ON)
OPTION(USB_SERIAL_SERVICE "Use USB Serial if Available" ON)
OPTION(USE_FAT_INSTEAD_OF_LITTLEFS "Use FAT instead of LittleFS" OFF)

# #######################################
# Do not change anything below this line
# #######################################
cmake_minimum_required(VERSION 3.12.4)
set(CMAKE_CXX_STANDARD 20)

include (cmake/targets.cmake)

include($ENV{IDF_PATH}/tools/cmake/project.cmake)

include (cmake/features.cmake)

project(ESP3D-TFT
    VERSION 1.0
    DESCRIPTION "ESP3D TFT")
```
I cannot duplicate
image

No error and USB communication is working
image

**Comment by liqijian101** [comment]
Under the condition of disabling the camera and TFT, ESP3D-TFT can indeed work. I set the wrong baud rate, which is why the above error occurred.
ESP3D-TFT can work when the camera is enabled but TFT is disabled.
If the camera and TFT are enabled, ESP3D TFT will continue to run incorrectly。
I don't think TFT is necessary。
The camera and USBHOST are a better combination. This will save money on touch screens

**Comment by luc-github** [comment]
>I set the wrong baud rate, which is why the above error occurred. 

I did also and cannot duplicate the issue, communication failed but no such error

>If the camera and TFT are enabled, ESP3D TFT will continue to run incorrectly。

That not clear - what the issue ? error ? performances ? crash ? please elaborate

>The camera and USBHOST are a better combination. This will save money on touch screens

That is Seeed studio Xiao sense S3 = 15$

**Comment by liqijian101** [comment]
> I did also and cannot duplicate the issue, communication failed but no such error
I just tested it again, and the program can run normally. It's so weird。Anyway, thank you very much


> That is Seeed studio Xiao sense S3 = 15$
This is great, but if I design a DIY capable motherboard, the cost is only $7 in China


> That not clear - what the issue ? error ? performances ? crash ? please elaborate

ESP_ERROR_CHECK failed: esp_err_t 0x105 (ESP_ERR_NOT_FOUND) at 0x42084661
file: "./managed_components/espressif__usb_host_cdc_acm/cdc_acm_host.c" line 897
func: cdc_acm_host_close
expression: cdc_acm_reset_transfer_endpoint(cdc_dev->dev_hdl, cdc_dev->data.in_xfer)

**Comment by liqijian101** [comment]
I have found the reason. It's because my 3D printer motherboard has insufficient output power and cannot drive the screen

**Comment by luc-github** [comment]
> I have found the reason. It's because my 3D printer motherboard has insufficient output power and cannot drive the screen

that make sense, on my side I always external power the tft, usb is only for communication

**Comment by luc-github** [comment]
So do you considere the PR is now Ok and can be merged ?

**Comment by liqijian101** [comment]
The pr is ok .it can be merged.

**Pull request merged**
