### PR TITLE
Add camera function to BZM motherboard

### PR DESCRIPTION
**Pull request by liqijian101**
Camera using OV2640

### CODE REVIEW

**Comment by luc-github** [comment]
is that working ?
I see    `pinMode`, `digitalWrite` and other API that is Arduino specific and not in IDF

**Comment by liqijian101** [comment]
I have  solved it.

**Comment by luc-github** [comment]
you need to add handler counter value for snap handler like : https://github.com/luc-github/ESP3D-TFT/blob/main/main/modules/http/esp3d_http_service.cpp#L39-L43
and add it here : https://github.com/luc-github/ESP3D-TFT/blob/main/main/modules/http/esp3d_http_service.cpp#L237

Do you plan to add camera related commands also ? 
[ESP170]https://esp3d.io/esp3d/v3.x/documentation/commands/esp170/index.html
[ESP171]https://esp3d.io/esp3d/v3.x/documentation/commands/esp171/index.html

**Comment by liqijian101** [comment]
I have add handler counter value,but I dont Know Why to add it.
I plan to add  related commands,but I am not goot at the code.

**Comment by luc-github** [comment]
> I have add handler counter value,but I dont Know Why to add it.

This is related to IDF API you need to set how many handler you have in top of adding handler or the latest handler won't be add and won't be used

> I plan to add related commands,but I am not goot at the code.

It is ok you did well and you can use same code as ESP3D as code base, as you did, they should be almost compatible

**Comment by liqijian101** [comment]
Hi luc,
I tried adding 170 commands，But it always failde to compile.
So I will not add any related commands.
I hope to PR now.

**Comment by luc-github** [comment]
ok I will have a look - thank you

**Comment by luc-github** [comment]
why did you closed the PR ?

**Comment by liqijian101** [comment]
I mistakenly received the lvgl9 branch.I am changing the code and restoring the previous program. Afterwards, I will resubmit Pr

**Comment by luc-github** [comment]
Ok - the lvgl 90 is definitly not for short terms so ignore it pls

**Pull request closed without merging**
