### PR TITLE
Add new board ESP32S3_BZM_TFT35_GT911 

### PR DESCRIPTION
**Pull request by liqijian101**

### CODE REVIEW

**Comment by luc-github** [comment]
Hi @liqijian101 is `panlee` name not already used ? or does it  has a meaning ?
Do you also plan to add page to http://esp3d.io/esp3d-tft/v1.x/hardware/index.html ? it would be helpful for everyone

**Comment by liqijian101** [comment]
Yes,I will share my  board.it is more cheap.

**Comment by liqijian101** [comment]
I will provide a link for web sharing

**Comment by luc-github** [comment]
Ok - you may also be interrested to https://github.com/luc-github/ESP3D-TFT/pull/30 to add support of interrupt  support of GT911 touch driver

**Comment by liqijian101** [comment]
ESP32_3248S035C and ESP32_3248S035R  should be similar to mine, maybe I can use this board without having to submit a new PR

**Comment by luc-github** [comment]
your's is ESP32S3 not ESP32 (ESP32_3248S035C and ESP32_3248S035R) and his PR () affect only drivers GT911, you may just need to update your drivers and touch definition if your board has interrupt pin connected to GT911

**Comment by luc-github** [comment]
So do you want me to wait for esp3d.io page addition before merging ?

**Comment by liqijian101** [comment]
> So do you want me to wait for esp3d.io page addition before merging ?

I hope to merge now, after testing for a period of time, I will share my board and add it to  esp3d.io page

**Comment by luc-github** [comment]
Merged

**Pull request merged**
